

---
title: "Supplementary Information: Models"
author: "Laura Geronimo"
output:
  html_document:
    toc: true
    toc_depth: 6
    theme: united

---
## Notest
This file needs work. Need to do ds, svss, and stepwise selection specific to NB model


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
##Libraries

library(ggplot2)
library(dplyr)
library(caret)

library(pacman)
library(stringr)

library(Hmisc)
library(tidycensus)
library(tidyverse)
library(corrplot)
library(data.table)
library(pastecs)
library(car)
library(gvlma)
library(qcc)
library(stargazer)

library(forcats)
library(boot)
library(bootstrap)
library(fixest)
library(lmtest)
library(sandwich)
library(cowplot)

library(pROC)
library(MASS)

library(SSVS)


options (scipen=999)

#importing data
DNZV1 <- read.csv('C:/Users/lgero/Box/Research/FEMA_project/Data/Edited/HMA/DNZLevel/DNZ_V1/DNZ_V1.csv')
names(DNZV1)
DNZV1 <- DNZV1[,c(-1)]

#creating subsets
DNZV1_lessMix <- subset(DNZV1, felev==0 | felev==1)
DNZV1_Mix <- subset(DNZV1, felev>0 & felev<1)

DNZV1_ZCTAshore <- subset(DNZV1, ZCTA_shore==1) 
DNZV1_After1993 <- subset(DNZV1, fyDeclared>1993)
DNZV1_Katrina <- subset(DNZV1, HurricaneName=="katrina") 
DNZV1_Sandy <- subset(DNZV1, HurricaneName=="sandy") 


```


# Negative binomial on elev counts - Full Set (SVSS vars from felev)
```{r include=FALSE}
# Load necessary libraries
library(MASS)
library(stargazer)

# Fit Negative Binomial regression model
nb_model <- glm.nb(Elev ~ count_fema_sfha_W_1k + Hurricane + MHVadj_W_100k + ZCTA_shore +
                   MHIadj_W_10k + fWhite + RepRate + TaxBaseEst_1B_W +
                   NFIP_ICCadj_YOLZ_W_1M + mrp_ideology + fWhite +
                   factor(StateNumLG) + factor(fyDeclared),
                 data=DNZV1)

# Summary of the model
summary(nb_model)

# Exponentiate the coefficients
exp_coef <- exp(coef(nb_model))
exp_coef_df <- data.frame(
  Predictor = names(exp_coef),
  Exp_Coefficient = exp_coef
)
print(exp_coef_df)

# Exponentiate the confidence intervals
confint_nb_model <- exp(confint(nb_model))
confint_df <- data.frame(
  Predictor = rownames(confint_nb_model),
  Lower_CI = confint_nb_model[, 1],
  Upper_CI = confint_nb_model[, 2]
)
print(confint_df)

# Combine the exponentiated coefficients and their confidence intervals
results_df <- merge(exp_coef_df, confint_df, by = "Predictor")
print(results_df)

# Display model summary with stargazer
library(stargazer)
stargazer(nb_model, type="html",
          omit=c("StateNumLG", "fyDeclared"), 
          apply.coef=exp,
          apply.ci=exp,
          t.auto=F,
          p.auto=F,
          title="Negative Binomial Regression Model for Count of Elevations - Full Set",
          dep.var.labels = c("Count of Elevations"),
          digits=2,
          column.sep.width = "10pt",
          single.row = FALSE,
          align=TRUE,
          out="C:/Users/lgero/Box/Research/FEMA_project/Results/myHMA10/DNZ_V1/fs_nb_elev.htm")
```


# Negative binomial on elev counts - Full Set (SVSS vars from felev)
```{r include=FALSE}
# Load necessary libraries
library(MASS)
library(stargazer)

# Fit Negative Binomial regression model
nb_model <- glm.nb(Elev ~ count_fema_sfha_W_1k + Hurricane + MHVadj_W_100k + 
                   MHIadj_W_10k + fWhite + RepRate + TaxBaseEst_1B_W +
                   NFIP_ICCadj_YOLZ_W_1M + mrp_ideology + fWhite +
                   factor(StateNumLG) + factor(fyDeclared),
                 data=DNZV1_ZCTAshore)

# Summary of the model
summary(nb_model)

# Exponentiate the coefficients
exp_coef <- exp(coef(nb_model))
exp_coef_df <- data.frame(
  Predictor = names(exp_coef),
  Exp_Coefficient = exp_coef
)
print(exp_coef_df)

# Exponentiate the confidence intervals
confint_nb_model <- exp(confint(nb_model))
confint_df <- data.frame(
  Predictor = rownames(confint_nb_model),
  Lower_CI = confint_nb_model[, 1],
  Upper_CI = confint_nb_model[, 2]
)
print(confint_df)

# Combine the exponentiated coefficients and their confidence intervals
results_df <- merge(exp_coef_df, confint_df, by = "Predictor")
print(results_df)

# Display model summary with stargazer
library(stargazer)
stargazer(nb_model, type="html",
          omit=c("StateNumLG", "fyDeclared"), 
          apply.coef=exp,
          apply.ci=exp,
          t.auto=F,
          p.auto=F,
          title="Negative Binomial Regression Model for Count of Elevations - Shore Set",
          dep.var.labels = c("Count of Elevations"),
          digits=2,
          column.sep.width = "10pt",
          single.row = FALSE,
          align=TRUE,
          out="C:/Users/lgero/Box/Research/FEMA_project/Results/myHMA10/DNZ_V1/zs_nb_elev.htm")
```

